"""
Indicator accuracy scores, signal descriptions, and trading context.
Based on backtesting research and market standard definitions.
"""

INDICATOR_ACCURACY = {
    "ema": {
        "accuracy_score": 72,
        "bull_signal": "Price closes above both EMA 50 and EMA 200 (golden cross alignment). Strong green candle closing above both lines confirms trend.",
        "bear_signal": "Price closes below EMA 200 (death cross). EMA 50 crossing below EMA 200 confirms aggressive downtrend.",
        "what_to_watch": "Watch the angle of EMA slope — steep = strong momentum, flat = weak. In sideways markets, EMA gives false signals. Best paired with volume confirmation.",
        "best_for": "Swing & positional trades",
    },
    "rsi": {
        "accuracy_score": 78,
        "bull_signal": "RSI between 50-65 on a strong green candle — sweet spot for swing entry. RSI bouncing off 40-50 zone in an uptrend = pullback buy.",
        "bear_signal": "RSI below 30 with red candle closing near low = oversold but still weak. RSI falling from 70+ = momentum exhaustion.",
        "what_to_watch": "Divergence is the most powerful RSI signal. Price makes new low but RSI doesn't = hidden bullish divergence. RSI above 70 in strong trends is NOT a sell signal.",
        "best_for": "All timeframes",
    },
    "macd": {
        "accuracy_score": 71,
        "bull_signal": "MACD histogram crosses above zero with expanding bars. Green candle on crossover day = strong confirmation.",
        "bear_signal": "MACD histogram crosses below zero. Shrinking positive histogram = fading momentum warning before actual crossover.",
        "what_to_watch": "Histogram expansion matters more than the crossover itself. Watch for divergence — price at new high but MACD at lower high = weakening momentum.",
        "best_for": "Swing trades",
    },
    "volume_surge": {
        "accuracy_score": 68,
        "bull_signal": "Volume ≥ 1.5x 20-day average on a green candle closing near high = institutional buying. Breakout + volume surge = confirmed move.",
        "bear_signal": "Volume spike on red candle closing near low = distribution. Rising price with declining volume = weak rally likely to reverse.",
        "what_to_watch": "Green candle + volume surge = strongest signal. Red candle + surge = distribution. Doji + surge = indecision, avoid. Context with support/resistance is critical.",
        "best_for": "Breakout confirmation",
    },
    "supertrend": {
        "accuracy_score": 81,
        "bull_signal": "Price closes and stays above Supertrend line (line turns green). Strong candle breaking above with volume = high conviction entry.",
        "bear_signal": "Price crosses below Supertrend line (line turns red). Use as trailing stop-loss — exit when line flips.",
        "what_to_watch": "One of the most reliable indicators. Use as dynamic support/resistance and trailing stop. Fails in choppy sideways markets. Supertrend + volume confirmation = 85-90% accuracy.",
        "best_for": "Trending markets, stop-loss placement",
    },
    "adx": {
        "accuracy_score": 74,
        "bull_signal": "ADX ≥ 25 with +DI above -DI = strong bullish trend confirmed. ADX rising from below 20 = trend emerging.",
        "bear_signal": "ADX ≥ 25 with -DI above +DI = strong bearish trend. ADX below 20 = no trend, choppy market — avoid trend trades.",
        "what_to_watch": "ADX tells trend STRENGTH not direction. ADX 0-20 = avoid, 20-25 = emerging, 25-50 = strong, 50+ = very strong but near exhaustion. Declining ADX while price rises = momentum fading.",
        "best_for": "Trend strength filter",
    },
    "obv": {
        "accuracy_score": 70,
        "bull_signal": "OBV rising while price consolidates = accumulation (smart money buying before breakout). OBV at new highs before price = leading signal.",
        "bear_signal": "OBV falling while price holds = distribution (smart money exiting). OBV divergence from price = reversal warning.",
        "what_to_watch": "OBV divergence is the key signal — when OBV disagrees with price, OBV is right 75% of the time. OBV leads price by 2-3 bars. Better as confirmation than standalone.",
        "best_for": "Accumulation/distribution detection",
    },
    "cmf": {
        "accuracy_score": 69,
        "bull_signal": "CMF ≥ 0.1 = money flowing into stock. Rising CMF over 3-5 bars = building buying conviction. Green candle closing near high + positive CMF = strongest.",
        "bear_signal": "CMF < 0 = money flowing out. CMF divergence with price at new highs = institutional selling.",
        "what_to_watch": "CMF measures where price closes within the day's range. Close near high = accumulation, close near low = distribution. More reliable on daily timeframes.",
        "best_for": "Money flow confirmation",
    },
    "roc": {
        "accuracy_score": 66,
        "bull_signal": "ROC > 0 and rising = accelerating upward momentum. ROC crossing above zero on green candle = early entry signal.",
        "bear_signal": "ROC < 0 = price falling. ROC at extreme highs = mean reversion likely (price will pull back).",
        "what_to_watch": "ROC divergence — price at new high but ROC lower = momentum failing. Extreme ROC values signal mean reversion. Better for contrarian trades than trend following.",
        "best_for": "Momentum measurement",
    },
    "awesome_oscillator": {
        "accuracy_score": 75,
        "bull_signal": "AO crossing from negative to positive = trend reversal. 'Saucer' pattern (green-red-green in positive territory) = high-probability entry.",
        "bear_signal": "AO crossing below zero = bearish momentum. Declining green bars = fading momentum warning.",
        "what_to_watch": "Zero-line crossover is the primary signal. The 'saucer' pattern (small dip in positive AO) has 78-85% accuracy. Watch histogram color changes for momentum shifts.",
        "best_for": "Momentum reversals",
    },
    "anchored_vwap": {
        "accuracy_score": 77,
        "bull_signal": "Price closes above anchored VWAP from last swing low = trend intact. Bounce off VWAP = support confirmation (80-85% success rate).",
        "bear_signal": "Price breaks below anchored VWAP = support lost, trend reversal warning.",
        "what_to_watch": "Acts as dynamic support/resistance from a meaningful price level. Distance from VWAP tells trend strength. Better than moving averages because anchored to a real swing point.",
        "best_for": "Dynamic support/resistance",
    },
    "pivot_levels": {
        "accuracy_score": 72,
        "bull_signal": "Price closes above pivot point (PP) and holds. Green candle bouncing off S1 support = reversal entry.",
        "bear_signal": "Price breaks below S1 support. Rejection at R1/R2 resistance = bearish continuation.",
        "what_to_watch": "Pivots act as natural support/resistance — self-fulfilling because institutional traders use them. Monthly pivots for short-term, quarterly for intermediate trades. Bounce off S1/R1 has highest probability.",
        "best_for": "Support/resistance levels",
    },
    "hidden_divergence": {
        "accuracy_score": 79,
        "bull_signal": "Price makes higher low but RSI makes lower low = hidden bullish divergence. Trend continuation — the pullback is a buying opportunity.",
        "bear_signal": "Price makes lower high but RSI makes higher high = hidden bearish divergence. Rally is a selling opportunity.",
        "what_to_watch": "Hidden divergence = trend CONTINUATION (different from regular divergence which is reversal). More reliable than regular divergences. Forms over 3-5 candles minimum. Entry on the candle after divergence completes.",
        "best_for": "High-conviction trend continuation",
    },
    "sector_performance": {
        "accuracy_score": 68,
        "bull_signal": "Sector outperforms Nifty over 30 days = tailwind for individual stocks. Only trade bullish stocks in bullish sectors.",
        "bear_signal": "Sector underperforms Nifty = headwind. Avoid buying even strong stocks in weak sectors.",
        "what_to_watch": "Use as a FILTER not a signal. Sector rotation patterns help identify which groups to focus on. If individual stock is green but sector is red = rejection risk.",
        "best_for": "Sector rotation filter",
    },
    "fisher_transform": {
        "accuracy_score": 82,
        "bull_signal": "Fisher value crosses above signal line with Fisher > 0 = turning point with bullish momentum. Extreme negative Fisher reversing = powerful buy.",
        "bear_signal": "Fisher crosses below signal line with Fisher < 0 = bearish turning point. Fisher > 2 = extreme, reversal likely.",
        "what_to_watch": "One of the HIGHEST accuracy indicators for swing trading. Turning points are sharp and clear. Leading indicator — turns 1-2 bars before price. Double-top/bottom in Fisher = very high probability reversal.",
        "best_for": "Swing trading turning points",
    },
    "klinger_oscillator": {
        "accuracy_score": 80,
        "bull_signal": "KVO crosses above signal line with KVO > 0 = volume force turning bullish. High-volume green candle on crossover = strongest setup.",
        "bear_signal": "KVO crosses below signal line = volume force bearish. KVO divergence with price = smart money exiting.",
        "what_to_watch": "Combines price direction + volume force — more powerful than volume alone. KVO divergence has 84-90% accuracy. Watch the rate of KVO change — fast acceleration = momentum building.",
        "best_for": "Volume-weighted momentum",
    },
    "chande_momentum": {
        "accuracy_score": 76,
        "bull_signal": "CMO in 10-50 range and rising = momentum in sweet spot. CMO crossing above zero on green candle = bullish shift.",
        "bear_signal": "CMO below 10 or above 50 = extremes, reversal likely. CMO declining while price rises = momentum failure.",
        "what_to_watch": "More responsive than RSI — catches momentum shifts 2-3 bars faster. Zero line crossing is key. CMO divergence with price = strong reversal signal. Works well on faster timeframes (4H, 1H).",
        "best_for": "Fast momentum detection",
    },
    "force_index": {
        "accuracy_score": 77,
        "bull_signal": "Force Index crosses above zero = price-volume force turning bullish. Rising Force Index = conviction increasing. Green high-volume candle with rising FI = strong entry.",
        "bear_signal": "Force Index below zero = bearish force. Extreme negative values = exhaustion (potential reversal).",
        "what_to_watch": "Combines price change × volume × EMA — captures all three momentum drivers. Extreme values signal exhaustion. FI divergence with price = force weakening, reversal setup.",
        "best_for": "Price-volume force measurement",
    },
    "vortex": {
        "accuracy_score": 81,
        "bull_signal": "+VI crosses above -VI = bullish trend change. Wide spread between +VI and -VI (>0.2) = very strong trend. Hold position.",
        "bear_signal": "-VI crosses above +VI = bearish trend change. Intertwined VI lines = choppy market, avoid.",
        "what_to_watch": "VI spread = trend strength. Clean separation of +VI/-VI = strong trend. Excellent on breakout trades — rides the entire trend. One of the most underrated indicators. VI + Supertrend confluence = 85-90% accuracy.",
        "best_for": "Trend breakouts",
    },
    # Fundamentals
    "roe": {
        "accuracy_score": 74,
        "bull_signal": "ROE ≥ 12% and rising YoY = profitable company improving capital deployment. ROE 20%+ consistently = exceptional business.",
        "bear_signal": "ROE < 12% or declining = capital inefficiency. High ROE from high leverage (check D/E) = false signal.",
        "what_to_watch": "Compare within sector — ROE 20% in banking is average, 20% in manufacturing is exceptional. Rising ROE > static high ROE. Watch if ROE is inflated by debt (check D/E ratio).",
        "best_for": "Quality screening",
    },
    "roce": {
        "accuracy_score": 76,
        "bull_signal": "ROCE ≥ 10% = efficient capital use. ROCE > WACC = company creating value. Rising ROCE for 5+ years = fortress company.",
        "bear_signal": "ROCE < 10% = capital waste. Declining ROCE = deteriorating business quality.",
        "what_to_watch": "ROCE includes all capital (debt + equity) — harder to manipulate than ROE. High ROCE + low ROE = leverage masking poor operations. ROCE > 12% for 5+ years = pricing power.",
        "best_for": "Capital efficiency analysis",
    },
    "debt_to_equity": {
        "accuracy_score": 72,
        "bull_signal": "D/E ≤ 1.0 = manageable debt. Declining D/E trend = debt paydown (bullish). Low D/E + high ROE = ideal combination.",
        "bear_signal": "D/E > 2.0 = high leverage risk. Rising D/E = borrowing aggressively. D/E > 2.5 = covenant violation risk.",
        "what_to_watch": "Sector-specific norms — banks 5-10x is normal, manufacturing 0.5-1.5x. Use as exclusion filter (high D/E = avoid) rather than buy signal. Check interest coverage ratio alongside.",
        "best_for": "Risk screening",
    },
    "eps": {
        "accuracy_score": 70,
        "bull_signal": "EPS > 0 and growing 20%+ YoY = strong earnings momentum. Accelerating EPS growth (10% → 15% → 25%) = strongest signal.",
        "bear_signal": "EPS < 0 or declining = losses or shrinking profitability. Decelerating EPS growth = momentum fading.",
        "what_to_watch": "EPS quality matters — cash-backed EPS > accrual-backed. EPS surprises (beating estimates) often trigger 3-5% rallies. Watch forward EPS estimates for next 2 quarters.",
        "best_for": "Earnings momentum",
    },
    "free_cash_flow": {
        "accuracy_score": 78,
        "bull_signal": "FCF > 0 and growing = cash-generating machine. FCF yield > 5% (FCF/Market Cap) = potentially undervalued.",
        "bear_signal": "FCF < 0 = burning cash, unsustainable model. Profit > FCF = lower quality earnings (accruals).",
        "what_to_watch": "Most reliable fundamental metric — hardest to fake. FCF must grow with revenue. Dividend > FCF = eventual cut coming. FCF + low valuation + technicals = highest conviction combination.",
        "best_for": "Cash flow quality analysis",
    },
    "institutional_holdings": {
        "accuracy_score": 65,
        "bull_signal": "Institutional ownership rising = smart money accumulating. 10-15% jump in holdings often precedes rally.",
        "bear_signal": "Declining institutional ownership = smart money exiting. Major fund holder exit = thesis changed.",
        "what_to_watch": "Slow 1-2% quarterly rise = stealth buying (very bullish long-term). Both insider + institutional buying = strongest signal. Data availability limited for many NSE stocks.",
        "best_for": "Long-term conviction filter",
    },
    # Breakout indicators
    "breakout_proximity": {
        "accuracy_score": 73,
        "bull_signal": "Price within 5% of 52-week high = breakout zone. Volume increasing as price approaches high = building pressure.",
        "bear_signal": "Price far from highs with declining volume = no breakout momentum.",
        "what_to_watch": "Proximity alone doesn't mean breakout will happen. Need volume confirmation + RSI in 55-65 zone. Multiple touches of resistance before breakout = stronger signal.",
        "best_for": "Breakout screening",
    },
    "breakout_volume": {
        "accuracy_score": 70,
        "bull_signal": "Volume ≥ 2x average on breakout day = confirmed institutional participation. Volume precedes price — surge before breakout = early signal.",
        "bear_signal": "Breakout on low volume = false breakout (likely to fail and reverse).",
        "what_to_watch": "Volume multiplier of 2x+ on breakout day is the gold standard. Check if volume sustains for 2-3 days post-breakout. Single day volume spike that fades = trap.",
        "best_for": "Breakout validation",
    },
    "bb_squeeze": {
        "accuracy_score": 74,
        "bull_signal": "Bollinger Bands squeezing tight (bandwidth at 6-month low) = volatility compression. Expansion after squeeze = directional move starting.",
        "bear_signal": "Bands expanding rapidly after squeeze in downward direction = bearish breakout.",
        "what_to_watch": "The squeeze itself is neutral — it tells you a big move is COMING but not which direction. Use other indicators (RSI, MACD) to determine direction. Squeeze + volume surge = highest conviction.",
        "best_for": "Volatility breakout timing",
    },
    "stochastic_rsi": {
        "accuracy_score": 73,
        "bull_signal": "%K crosses above %D below 20 = oversold reversal. Both lines rising from oversold = momentum building.",
        "bear_signal": "%K crosses below %D above 80 = overbought reversal. Both lines falling from overbought = momentum fading.",
        "what_to_watch": "More sensitive than regular RSI — catches reversals earlier but more false signals. Best in ranging markets. In strong trends, can stay overbought/oversold for extended periods.",
        "best_for": "Overbought/oversold reversals",
    },
    "williams_r": {
        "accuracy_score": 71,
        "bull_signal": "Williams %R crossing above -80 from below = oversold reversal starting. Rising from extreme oversold = building momentum.",
        "bear_signal": "Williams %R crossing below -20 from above = overbought reversal. Failing at -20 = resistance rejection.",
        "what_to_watch": "Ranges from 0 to -100. Above -20 = overbought, below -80 = oversold. Similar to Stochastic but inverted scale. Works best with support/resistance confluence.",
        "best_for": "Reversal timing",
    },
    "supply_zone": {
        "accuracy_score": 71,
        "bull_signal": "Price approaching supply zone with weakening volume = resistance may hold. Break above supply zone with volume = powerful breakout.",
        "bear_signal": "Price rejected from supply zone = selling pressure. Multiple rejections = strong resistance.",
        "what_to_watch": "Supply zones form where previous selling occurred. More touches = weaker zone (eventually breaks). Fresh supply zones (untested) = strongest resistance.",
        "best_for": "Supply/demand analysis",
    },
    "institutional_flow": {
        "accuracy_score": 67,
        "bull_signal": "Large block trades on uptick = institutional buying. Unusual volume patterns at support = accumulation.",
        "bear_signal": "Large block trades on downtick = institutional selling. Volume spikes at resistance without breakout = distribution.",
        "what_to_watch": "Institutional footprint shows in volume patterns and order flow. Large orders often execute over 2-3 days. Watch for unusual activity near earnings or events.",
        "best_for": "Smart money tracking",
    },
    "ichimoku": {
        "accuracy_score": 76,
        "bull_signal": "Price above cloud (Kumo), Tenkan above Kijun, cloud green = triple bullish confirmation. Chikou span above price = strongest.",
        "bear_signal": "Price below cloud, Tenkan below Kijun, cloud red = triple bearish. Price entering cloud = trend weakening.",
        "what_to_watch": "Cloud thickness = support/resistance strength. Thin cloud = easy breakout, thick cloud = strong barrier. Cloud twist (color change) = potential trend reversal ahead. Works best on daily+ timeframes.",
        "best_for": "Complete trend analysis system",
    },
    "vwap_bands": {
        "accuracy_score": 79,
        "bull_signal": "Price within +1σ to +2σ of VWAP = contained bullish momentum. Breakout above +1σ with volume = trend acceleration.",
        "bear_signal": "Price below -1σ = breakdown confirmed. Price at -2σ = extreme, mean reversion likely within 2-5 candles.",
        "what_to_watch": "Sigma bands adjust to volatility. Band squeeze = big move coming. VWAP itself = dynamic support. Price 2σ+ away = likely to revert to mean. Very reliable on trending days.",
        "best_for": "Intraday/swing momentum bands",
    },
}
